services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: llpp_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  back:
    build:
      context: ./backend #Dockerファイルがあるディレクトリパスを指定
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'" #コンテナが起動するときに実行されるコマンドを指定
    volumes:
      - ./backend:/app
    ports:
      - "3003:3000"
    depends_on: #db→Railsの順に起動するように設定
      - db
    tty: true
    stdin_open: true
    environment:
      - RAILS_ENV=development
      - CORS_ALLOWED_ORIGINS=localhost:8000,127.0.0.1:8000
    networks:
      default:
        aliases:
          - api  # backサービスに「api」という別名を追加
  front:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "yarn install && yarn dev -p 4000"
    ports:
      - "8000:4000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3003
    depends_on:
      - back
    networks:
      - default
volumes:
  postgres_data:
